#!/system/bin/sh

# ---> dtrail (D-WiZ 1.00) (c)2012
#
## JBX-Kernel 2.0 V12_01  (c)*dtrail
# *Based on MR1-JB Kernel (Motorola/STS-Dev-Team/Hashcode)
#
#
# Setting up kernel and memory tweaks
# Shut down nmi watchdog
# slow down kernel latency
#
#

echo "0" > /sys/kernel/hdmi/hdmi_active;
